name: Debezium crypto image build
on:
  push:
    branches:
      - "main"

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: GraalVM 21.2.0
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.2.0
          native-image: true

      # Skipping tests for now, as there are none
      - name: Build native
        run: ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dskip.tests

      #- name: Build docker image
      #  run: docker build -f src/main/docker/Dockerfile.native -t quay.io/tealc/debezium-crypto-app .

      - name: Login to quay.io Hub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/tealc/debezium-crypto-app:latest
          file: ./src/main/docker/Dockerfile.native
          context: ./
